name: proyecto-ia

channels:
  - conda-forge
  - pytorch
  - defaults

dependencies:
  - python=3.11

  # Ciencia de datos
  - numpy
  - pandas

  # Visualización
  - matplotlib

  # Visión computacional
  - opencv

  # Deep Learning
  - pytorch
  - torchvision
  - torchaudio

  # Notebooks
  - notebook
  - jupyterlab
  - ipykernel

  # Utilidades
  - tqdm
  - pillow

  # Pip
  - pip

  - pip:
      - ultralytics
